// app/(web)/terms/page.tsx
"use client";

import { AnimatedSection } from "@/components/AnimatedSection";
import Link from "next/link";

const Section = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => (
  <div className="py-6">
    <h2 className="text-2xl font-bold font-heading mb-4">{title}</h2>
    <div className="space-y-4 text-light-text-secondary dark:text-dark-text-secondary">
      {children}
    </div>
  </div>
);

export default function TermsPage() {
  const lastUpdated = "July 10, 2025";

  return (
    <main className="bg-background">
      <div className="container mx-auto max-w-3xl px-6 py-32 sm:py-40">
        <AnimatedSection>
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl font-heading">
              Terms of Service
            </h1>
            <p className="mt-4 text-light-text-secondary dark:text-dark-text-secondary">
              Last Updated: {lastUpdated}
            </p>
          </div>

          <div className="divide-y divide-light-border dark:divide-dark-border">
            <Section title="1. Introduction">
              <p>
                Welcome to AURA (&quot;Company&quot;, &quot;we&quot;, &quot;our&quot;, &quot;us&quot;). These Terms of
                Service (&quot;Terms&quot;) govern your use of our web application, APIs,
                and services (collectively, the &quot;Service&quot;). By accessing or
                using our Service, you agree to be bound by these Terms and our{" "}
                <Link
                  href="/privacy"
                  className="text-primary-default underline"
                >
                  Privacy Policy
                </Link>
                .
              </p>
              <Section title="1.1. AI-Powered Interactions">
                <p>
                  AURA uses artificial intelligence to simulate conversation.
                  While we aim to provide helpful, empathetic, and engaging
                  interactions, the responses you receive are generated by a
                  language model and not a real human. The AI is not a licensed
                  therapist, doctor, or professional advisor.
                </p>
              </Section>
            </Section>

            <Section title="2. Eligibility">
              <p>
                You must be at least 18 years old to use the Service. By
                agreeing to these Terms, you represent and warrant that you are
                of legal age to form a binding contract.
              </p>
            </Section>

            <Section title="3. User Accounts">
              <p>
                To access most features, you must register for an account. You
                agree to provide accurate, current, and complete information
                during registration and to update such information to keep it
                accurate. You are responsible for safeguarding your password and
                for all activities that occur under your account.
              </p>
            </Section>

            <Section title="4. Subscriptions and Payments">
              <p>
                The Service may offer paid subscription plans (&quot;Subscriptions&quot;).
                By purchasing a Subscription, you agree to pay the specified
                fees, which will be billed on a recurring basis. You may cancel
                your Subscription at any time through your account settings;
                however, we do not provide refunds or credits for any partial
                subscription periods.
              </p>
            </Section>

            <Section title="5. User Conduct and Responsibilities">
              <p>
                You agree not to use the Service to generate content that is
                unlawful, harmful, threatening, abusive, defamatory, obscene, or
                otherwise objectionable. You are solely responsible for the
                content you generate and your interactions. Prohibited actions
                include:
              </p>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  Engaging in any activity that violates any law or regulation.
                </li>
                <li>
                  Attempting to reverse-engineer, decompile, or otherwise access
                  the source code of the Service.
                </li>
                <li>
                  Using automated systems or software to extract data
                  (scraping).
                </li>
                <li>
                  Impersonating any person or entity or misrepresenting your
                  affiliation with a person or entity.
                </li>
              </ul>
            </Section>

            <Section title="6. Content and Intellectual Property">
              <p>
                <strong>Our IP:</strong> The Service and its original content,
                features, and functionality are and will remain the exclusive
                property of AURA and its licensors.
              </p>
              <p>
                <strong>Your Content:</strong> You retain ownership of the text
                and content you create while using the Service (&quot;User Content&quot;).
                By using the Service, you grant us a worldwide, non-exclusive,
                royalty-free license to use, store, reproduce, and display your
                User Content solely for the purpose of operating, providing, and
                improving the Service for you. This license does not grant us
                permission to sell your data or use it to train third-party AI
                models.
              </p>
            </Section>

            <Section title="7. Termination">
              <p>
                We may terminate or suspend your account and access to the
                Service immediately, without prior notice or liability, for any
                reason, including, but not limited to, a breach of these Terms.
                You may terminate your account at any time by deleting it from
                your account settings.
              </p>
            </Section>

            <Section title="8. Disclaimer of Warranties and Limitation of Liability">
              <p>
                The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis.
                We make no warranties, express or implied, regarding the
                operation or availability of the Service. To the fullest extent
                permissible by law, AURA shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages arising
                out of or in connection with your use of the Service.
              </p>
            </Section>

            <Section title="9. Changes to Terms">
              <p>
                We reserve the right to modify these Terms at any time. We will
                provide notice of material changes, such as by sending an email
                or posting a notice on our Service. Your continued use of the
                Service after such changes constitutes your acceptance of the
                new Terms.
              </p>
            </Section>

            <Section title="10. Contact Information">
              <p>
                If you have any questions about these Terms, please contact us
                at{" "}
                <Link
                //   href="mailto:support@aura-app.com"
                  href="/contact"
                  className="text-primary-default underline"
                >
                  Contact
                </Link>
                .
              </p>
            </Section>
          </div>
        </AnimatedSection>
      </div>
    </main>
  );
}